In [7]:
import sys
!{sys.executable} -m pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (2.4.1)
Requirement already satisfied: matplotlib in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\laksh\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\laksh\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\laksh\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\laksh\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Pandas version:", pd.__version__)

Pandas version: 3.0.0

In [8]:
df = pd.read_csv("../data/adult.csv")

df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [9]:
df.replace("?", np.nan, inplace=True)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [10]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [11]:
df.dtypes

age               int64
workclass           str
fnlwgt            int64
education           str
education.num     int64
marital.status      str
occupation          str
relationship        str
race                str
sex                 str
capital.gain      int64
capital.loss      int64
hours.per.week    int64
native.country      str
income              str
dtype: object

In [12]:
df.drop(columns=["fnlwgt"], inplace=True)
df.dtypes

age               int64
workclass           str
education           str
education.num     int64
marital.status      str
occupation          str
relationship        str
race                str
sex                 str
capital.gain      int64
capital.loss      int64
hours.per.week    int64
native.country      str
income              str
dtype: object

In [13]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include="object").columns

num_cols, cat_cols

C:\Users\laksh\AppData\Local\Temp\ipykernel_20552\741985943.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include="object").columns

(Index(['age', 'education.num', 'capital.gain', 'capital.loss',
        'hours.per.week'],
       dtype='str'),
 Index(['workclass', 'education', 'marital.status', 'occupation',
        'relationship', 'race', 'sex', 'native.country', 'income'],
       dtype='str'))

In [14]:
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [21]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [22]:
df.isnull().sum()

age               0
workclass         0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(3465)

In [18]:
df.duplicated().sum()

np.int64(3465)

In [19]:
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[num_cols] < (Q1 - 1.5 * IQR)) | 
          (df[num_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [20]:
# Data cleaning summary:
# Categorical missing values were handled using mode imputation

# Numerical columns had no missing values

# fnlwgt was removed due to lack of predictive relevance

# IQR-based outlier removal was applied to numerical feature

In [24]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [25]:
from categorical_encoding import (
    label_encoding,
    one_hot_encoding,
    ordinal_encoding,
    frequency_encoding,
    target_encoding
)

In [27]:
categorical_cols = df.select_dtypes(include="object").columns.tolist()

C:\Users\laksh\AppData\Local\Temp\ipykernel_20552\3833252215.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns.tolist()

In [28]:
df_label = label_encoding(df, categorical_cols)

In [29]:
df_onehot = one_hot_encoding(df, categorical_cols)

In [30]:
education_order = [
    ['Preschool', '1st-4th', '5th-6th', '7th-8th',
     '9th', '10th', '11th', '12th',
     'HS-grad', 'Some-college',
     'Assoc-voc', 'Assoc-acdm',
     'Bachelors', 'Masters', 'Prof-school', 'Doctorate']
]

df_ordinal = ordinal_encoding(df, ['education'], education_order)

In [31]:
df_frequency = frequency_encoding(df, categorical_cols)

In [32]:
df['income_binary'] = df['income'].map({'<=50K': 0, '>50K': 1})
df_target = target_encoding(df, 'education', 'income_binary')

In [ ]:
# Categorical Encoding Summary
# Different categorical encoding techniques were applied to demonstrate their suitability for various types of categorical features.

# Label Encoding was used for quick transformation of categorical values into numeric form, but it was noted that it may introduce unintended ordinal relationships for nominal variables.

# One-Hot Encoding was applied to nominal features such as workclass, occupation, race, and sex, as it prevents the model from assuming any inherent order among categories.

# Ordinal Encoding was specifically used for the education feature because it has a natural hierarchical order ranging from lower to higher educational qualifications.

# Frequency Encoding was used to replace categories with their occurrence frequencies, which helps retain information about category distribution without increasing dimensionality.

# Target Encoding was applied cautiously, as it uses the target variable to encode categories and may introduce data leakage if not handled properly. It was demonstrated only for educational purposes.

# All major encoding techniques were implemented to satisfy the assignment requirements and to compare their applicability across different types of categorical variables.

In [34]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, Normalizer

In [35]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

In [36]:
minmax_scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = minmax_scaler.fit_transform(df_minmax[num_cols])

In [37]:
maxabs_scaler = MaxAbsScaler()
df_maxabs = df.copy()
df_maxabs[num_cols] = maxabs_scaler.fit_transform(df_maxabs[num_cols])

In [38]:
standard_scaler = StandardScaler()
df_standard = df.copy()
df_standard[num_cols] = standard_scaler.fit_transform(df_standard[num_cols])

In [39]:
normalizer = Normalizer()
df_normalized = df.copy()
df_normalized[num_cols] = normalizer.fit_transform(df_normalized[num_cols])

In [40]:
df[num_cols].describe()
df_standard[num_cols].describe()

,age,education.num,capital.gain,capital.loss,hours.per.week,income_binary
count,1.961900e+04,1.961900e+04,19619.0,19619.0,1.961900e+04,1.961900e+04
mean,-6.374205e-17,3.904200e-16,0.0,0.0,3.045856e-16,-1.466791e-17
std,1.000025e+00,1.000025e+00,0.0,0.0,1.000025e+00,1.000025e+00
min,-1.744506e+00,-2.431578e+00,0.0,0.0,-2.145343e+00,-5.170062e-01
25%,-8.281439e-01,-5.757444e-01,0.0,0.0,-3.717780e-01,-5.170062e-01
50%,-7.839285e-02,-1.117861e-01,0.0,0.0,-3.717780e-01,-5.170062e-01
75%,6.713582e-01,8.161306e-01,0.0,0.0,-3.717780e-01,-5.170062e-01
max,3.337140e+00,2.671964e+00,0.0,0.0,2.668619e+00,1.934213e+00

In [42]:
# Feature Scaling Summary
# Feature scaling was applied to ensure that numerical features operate on comparable scales.

# Min-Max Scaling was used to transform values into a fixed range between 0 and 1, which is beneficial for distance-based algorithms.

# Max Absolute Scaling was applied to preserve sparsity and scale features based on their maximum absolute values.

# Z-score Standardization was used to center features around zero with unit variance, making it suitable for algorithms that assume normally distributed data.

# Vector Normalization was applied to scale individual data points to unit norm, which is useful in similarity-based models.

# All four scaling techniques were demonstrated to compare their effects on numerical features.

In [43]:
df['income_binary'] = df['income'].map({'<=50K': 0, '>50K': 1})

In [44]:
X = df.drop(columns=['income', 'income_binary'])
y = df['income_binary']

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [46]:
X_train.select_dtypes(include=["int64", "float64"]).skew()

age               0.445341
education.num     0.244571
capital.gain      0.000000
capital.loss      0.000000
hours.per.week    1.057729
dtype: float64

In [49]:
import numpy as np

for col in ['capital.gain', 'capital.loss']:
    X_train[col] = np.log1p(X_train[col])
    X_test[col] = np.log1p(X_test[col])

In [50]:
# Train-Test Split and Skewness Handling
# The dataset was split into training and testing sets using an 80–20 ratio to evaluate preprocessing consistency.

# Highly skewed numerical features such as capital gain and capital loss were identified using skewness statistics.

# Logarithmic transformation was applied to reduce skewness and stabilize variance, improving the suitability of these features for machine learning models.