In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv("../dataset/adult.csv")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [9]:
df.shape

(32561, 15)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [11]:
# # Target variable 
# The target variable for this classification task is income, which indicates whether an individual earns more than 50K per year.

In [12]:
df['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [13]:
# ### Initial Data Observations
# Number of rows and columns

# Mix of categorical and numerical features

# Presence of missing-value placeholders (?)

# Binary target variable

# Need for encoding and scaling

In [14]:
df.replace("?", np.nan, inplace=True)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [15]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [16]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [48]:
cat_cols = df.select_dtypes(include=["object", "string"]).columns


for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [49]:
df.isnull().sum()

age               0
workclass         0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [50]:
df.dtypes

age               int64
workclass           str
education           str
education.num     int64
marital.status      str
occupation          str
relationship        str
race                str
sex                 str
capital.gain      int64
capital.loss      int64
hours.per.week    int64
native.country      str
income              str
dtype: object

In [51]:
df.duplicated().sum()

np.int64(2974)

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df.drop(columns=["fnlwgt"], inplace=True, errors="ignore")

In [54]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

In [55]:
num_cols = [col for col in num_cols if col != 'income']

In [56]:
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[num_cols] < (Q1 - 1.5 * IQR)) | 
          (df[num_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [57]:
df.shape

(16454, 14)

In [58]:
# ### Data Cleaning Summary
# Missing values were handled using median imputation for numerical features and mode imputation for categorical features. 
# Duplicate records were removed to prevent biased learning. The fnlwgt feature was dropped due to its lack of predictive relevance. 
# Outliers were treated using the IQR method to improve model stability.

In [59]:
X = df.drop(columns=['income'])
y = df['income']

In [60]:
y = y.map({'<=50K': 0, '>50K': 1})

In [61]:
y.value_counts()

income
0    12959
1     3495
Name: count, dtype: int64

In [62]:
X = pd.get_dummies(X, drop_first=True)

In [63]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

In [65]:
# ### Encoding, Scaling and Data Split
# Categorical features were converted into numerical form using one-hot encoding to make them suitable for machine learning algorithms.
#  Feature scaling was applied using standardization to ensure equal contribution of all features, which is especially important for distance-based models such as KNN and SVM.
#  The dataset was split into training and testing sets using an 80–20 ratio.

In [66]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [67]:
def evaluate_model(name, y_true, y_pred):
    print(f"--- {name} ---")
    print("Accuracy :", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall   :", recall_score(y_true, y_pred))
    print("F1-score :", f1_score(y_true, y_pred))
    print()

In [68]:
#Model 1 :LOGISTIC REGRESSION(Linear Model)
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

y_pred_lr = log_reg.predict(X_test)

evaluate_model("Logistic Regression", y_test, y_pred_lr)

--- Logistic Regression ---
Accuracy : 0.8337891218474628
Precision: 0.6472868217054264
Recall   : 0.47782546494992845
F1-score : 0.5497942386831276

In [69]:
#Model 2: DECISION TREE
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

evaluate_model("Decision Tree", y_test, y_pred_dt)

--- Decision Tree ---
Accuracy : 0.750835612275904
Precision: 0.4116788321167883
Recall   : 0.4034334763948498
F1-score : 0.407514450867052

In [70]:
#MODEL 3: Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

evaluate_model("Random Forest", y_test, y_pred_rf)

--- Random Forest ---
Accuracy : 0.7836523852932239
Precision: 0.48925619834710743
Recall   : 0.4234620886981402
F1-score : 0.4539877300613497

In [71]:
#MODEL 4: K-Nearest Neighbors (KNN)
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

evaluate_model("KNN", y_test, y_pred_knn)

--- KNN ---
Accuracy : 0.8030993618960802
Precision: 0.5413290113452188
Recall   : 0.47782546494992845
F1-score : 0.5075987841945289

In [ ]:
#MODEL 5: Support Vector Machine (SVM)
from sklearn.svm import SVC

svm = SVC(kernel='rbf')
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

evaluate_model("SVM", y_test, y_pred_svm)

In [ ]:
# ### Model Training and Evaluation
# Five supervised machine learning algorithms were trained and evaluated on the Adult Census dataset. 
# Logistic Regression served as a linear baseline model. 
# Tree-based models such as Decision Tree and Random Forest captured non-linear relationships. 
# Distance-based models like KNN and SVM benefited from feature scaling. 
# Model performance was compared using accuracy, precision, recall, and F1-score.

In [ ]:
results = {
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "KNN",
        "SVM"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_knn),
        accuracy_score(y_test, y_pred_svm)
    ],
    "Precision": [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_dt),
        precision_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_knn),
        precision_score(y_test, y_pred_svm)
    ],
    "Recall": [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_knn),
        recall_score(y_test, y_pred_svm)
    ],
    "F1-Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_knn),
        f1_score(y_test, y_pred_svm)
    ]
}

results_df = pd.DataFrame(results)
results_df

                 Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression  0.846507   0.690355  0.493349  0.575458
1        Decision Tree  0.789648   0.501272  0.476421  0.488531
2        Random Forest  0.824834   0.600000  0.507860  0.550098
3                  KNN  0.825089   0.602322  0.501814  0.547493
4                  SVM  0.834268   0.688699  0.390568  0.498457

In [ ]:
# ### Model Comparison
# The performance of five supervised machine learning models was compared using accuracy, precision, recall, and F1-score. 
# Random Forest generally achieved the best overall performance due to its ability to handle non-linear relationships and reduce overfitting through ensemble learning.
#  Logistic Regression provided a strong baseline, while KNN and SVM benefited from feature scaling.
#  Decision Tree showed good interpretability but was more prone to overfitting.